spring.application.name=learning

#management.endpoints.web.exposure.include=health,info
management.endpoints.web.exposure.include=*
management.info.env.enabled=true

#management.endpoints.web.exposure.exclude=health,info

info.app.name=Learning App
info.app.description=cool and crazy app
info.app.version=1.0.0

coach.name=Mickey Mouse
team.name=The Mouse Club

#server.port=7070

server.servlet.context-path=/mycoolapp